### ISSUE TITLE
new install, example files will not run.

### ISSUE THREAD

**Issue by WiggyWire** [lefakkomies/pynomo#10]
So I try to run your own example programs after following the install guide for python 3. however nothing seems to work. All of the depency are installed. The system is running an up to date release of void linux. 
![pynomofail](https://user-images.githubusercontent.com/43072119/59870776-bcb17700-93c8-11e9-846e-13638e525ad6.png)

Is there something I can do to generate your example files? I would like to follow the tutorial pdf and make some of my own nomographs.

**Comment by WiggyWire** [comment]
I installed pynomo with python 2.7 and it works fine, it seems to be some issue with python3.

**Comment by lefakkomies** [comment]
It looks like an issue with numpy / python 3.6.
