### ISSUE TITLE
make_grid broken in python3

### ISSUE THREAD

**Issue by djboulet** [lefakkomies/pynomo#13]
The `'make_grid'` feature in `main_params` block seems broken under python3.  Inserting `'make_grid':True,` at line 117 in ex_BMI.py `main_params` block causes the following error:

> Traceback (most recent call last):
>   File "ex_BMI.py", line 120, in <module>
>     Nomographer(main_params)
>   File "../pynomo/nomographer.py", line 217, in __init__
>     self._make_grid_(params, c)
>   File "../pynomo/nomographer.py", line 250, in _make_grid_
>     Nomo_Axis(func_f=lambda u: u,
> NameError: name 'Nomo_Axis' is not defined

**Comment by lefakkomies** [comment]
Corrected by djboulet. Thanks!
