### ISSUE TITLE
v_title doesn't render on type 5 nomograph under certain conditions

### ISSUE THREAD

**Issue by djboulet** [lefakkomies/pynomo#16]
Using `ex_type5_nomo_1.py` as test code, `v_title` only renders if the number of elements in `v_values` is in the range 7 < _n_ < 13.

`v_title` renders with:

`'v_values': [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]` and 
`'v_values': [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0]`

but not with

`'v_values': [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0]` or 
`'v_values': [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0,13.0]`

`u_title` doesn't have the same limitation.

**Comment by djboulet** [comment]
An update ...
This nomograph ([voltdiv_E24_resistors.py](url)) properly renders `v_title` with **24** values in `u_values` and `v_values` lists.

[voltdiv_E24_resistors.pdf](https://github.com/lefakkomies/pynomo/files/4570314/voltdiv_E24_resistors.pdf)

**Comment by lefakkomies** [comment]
In my understanding comment above is enough to close the issue.
