### ISSUE TITLE
Issues aligning additional type 8 scales to f2 in a type 2 nomogram

### ISSUE THREAD

**Issue by devangel77b** [lefakkomies/pynomo#19]
I've been trying to design a Type 2 nomogram to compute design point from settling time and percent overshoot assuming second-order linear system type behavior. I am able to make it work as a Type 1 nomogram, but when I try to make it Type 2 i have odd issues where an additional type 8 scale that is aligned correctly when in the f1 or f3 position is not aligned in the f2 position. The only way I've been able to make this work is to make several Type 2 nomograms on top of each other with the different scales that should be aligned all as f2. 
[design-point-nomogram-type2.pdf](https://github.com/lefakkomies/pynomo/files/5513453/design-point-nomogram-type2.pdf)
[design-point-nomogram-type1.pdf](https://github.com/lefakkomies/pynomo/files/5513454/design-point-nomogram-type1.pdf)

**Comment by djboulet** [comment]
I'm working on additional documentation for axis alignment.  There are many moving parts.  Please post your python source for your nomograms.

**Comment by lefakkomies** [comment]
No source code posted. Unclear is it problem  when trying to align two scales with functionally different forms or something else. In N nomograph middle-scale is not uniform.  Closing due to lack of information for solving.
