### ISSUE TITLE
Issues rotating a scale 90 degrees? 

### ISSUE THREAD

**Issue by devangel77b** [lefakkomies/pynomo#20]
I am trying to make Type 8 scales to illustrate how to use a slide rule to do a calculation, but when I try a rotation transformation for -90 I get errors. +90 works, but -90 makes more sense for how the slide rule looks when used. 
[sliderule.pdf](https://github.com/lefakkomies/pynomo/files/5513461/sliderule.pdf)

**Comment by djboulet** [comment]
Here is something to consider ...

[slide_rule.pdf](https://github.com/lefakkomies/pynomo/files/6803714/slide_rule.pdf)

Source:

`
"""
    slide_rule.py

"""
from pynomo.nomographer import Nomographer
import sys

sys.path.insert(0, "..")
import numpy as np

N_params_1 = {
    "u_min": 1.0,
    "u_max": 100.0,
    "function": lambda u: np.log10(u),
    "extra_titles": [{"text": r"Scale A", "dx": -11.0, "dy": -8.0}],
    "tick_levels": 5,
    "tick_text_levels": 3,
    "extra_angle": 90.0,
    "title_x_shift": 10.0,
    "text_horizontal_align_center": True,
    "tick_side": "left",
    "scale_type": "linear smart",
}

block1_params = {
    "block_type": "type_8",
    "f_params": N_params_1,
    "width": 10 * 2.54,
    "height": 2 * 2.54,
    "mirror_y": True,
}
N_params_2 = {
    "u_min": 1,
    "u_max": 100.0,
    "function": lambda u: np.log10(u),
    "extra_titles": [{"text": r"Scale B", "dx": -9.0, "dy": -10.0}],
    "tick_levels": 5,
    "tick_text_levels": 3,
    "extra_angle": 90.0,
    "text_horizontal_align_center": True,
    "tick_side": "right",
    "scale_type": "linear smart",
}

block2_params = {
    "block_type": "type_8",
    "f_params": N_params_2,
    "width": 10 * 2.54,
    "height": 2 * 2.54,
    "mirror_y": True,
}

main_params = {
    "filename": "slide_rule.pdf",
    "block_params": [block1_params, block2_params],
    "transformations": [
        ("rotate", 90.01),
        ("scale paper",),
    ],
    # 'make_grid':True,
}

Nomographer(main_params)

`

**Comment by lefakkomies** [comment]
You can  use "function_x" and "function_y". Scaling does not really work well for 1-dimensional object (line). 
```python
"""
slide_rule.py

"""
from pynomo.nomographer import Nomographer
import sys
import pyx

sys.path.insert(0, "..")
import numpy as np

N_params_1 = {
    "u_min": 1.0,
    "u_max": 100.0,
    "function_x": lambda u: 1.0,
    "function_y": lambda u: np.log10(u) * 10,
    "extra_titles": [{"text": r"Scale A", "dx": -11.0, "dy": -8.0}],
    "tick_levels": 5,
    "tick_text_levels": 3,
    "extra_angle": 90.0,
    "title_x_shift": 10.0,
    "text_horizontal_align_center": True,
    "tick_side": "left",
    "scale_type": "linear smart",
    "tag": "a"
}

block1_params = {
    "block_type": "type_8",
    "f_params": N_params_1,
    "width": 10 * 2.54,
    "height": 2 * 2.54,
    "mirror_y": True,
}
N_params_2 = {
    "u_min": 1,
    "u_max": 100.0,
    "function_x": lambda u: 1.0,
    "function_y": lambda u: np.log10(u) * 10,
    "extra_titles": [{"text": r"Scale B", "dx": -9.0, "dy": -10.0}],
    "tick_levels": 5,
    "tick_text_levels": 3,
    "extra_angle": 90.0,
    "text_horizontal_align_center": True,
    "tick_side": "right",
    "scale_type": "linear smart",
    "tag": "a"
}

block2_params = {
    "block_type": "type_8",
    "f_params": N_params_2,
    "width": 10 * 2.54,
    "height": 2 * 2.54,
    "mirror_y": True,
}

main_params = {
    "filename": "slide_rule.pdf",
    "block_params": [block1_params, block2_params],
    'paper_height': 15.0,
    'paper_width': 25.0,
    "transformations": [
        ("rotate", 90.0),
        # ("scale paper",),
    ],
    'make_grid': True,
}

Nomographer(main_params)
```
