### ISSUE TITLE
Citation support?

### ISSUE THREAD

**Issue by jbrittonb** [lefakkomies/pynomo#22]
Hi, I've been using PyNomo for an academic project and would like to cite it properly but I don't know how I should do it in full.  Could a CITATION.cff file be added to the repository?
https://citation-file-format.github.io

Thank you,
Jason Brown

**Comment by lefakkomies** [comment]
Added. Thanks Jason for asking for this. 
br,
\leif

**Comment by jbrittonb** [comment]
Great, thank you!
