### ISSUE TITLE
Parallel scale (type 1) with unequal spacing

### ISSUE THREAD

**Issue by lfcybox** [lefakkomies/pynomo#27]
First, thank you so much for this project!
Working on a nomogram, I find that the parallel scale (type 1) would do the job, but I'd like to have the left axis at more distance, to make better use of its scale.
Is there a way to have unequal spacings between the three axis from a type 1 nomogram? 
Like as described in here: https://nomograms.blogspot.com/2023/01/note-parallel-scales-with-unequal.html

Thanks

**Comment by lefakkomies** [comment]
Try parameter 'proportion'.
[http://lefakkomies.github.io/pynomo-doc/types/types.html#type1-ref](url)

**Comment by lfcybox** [comment]
Thanks a lot! That's exactly it.
