### ISSUE TITLE
Colouring option does not work anymore

### ISSUE THREAD

**Issue by addlamorille** [lefakkomies/pynomo#31]
Hi, I have been using the Pynomo package for a while now, it truly is a wonderful tool.
I switched from the version 0.2.2 to the latest one (0.3.4) recently, to experiment the Nomogen script.
I ran the following commands to install the required packages :
```
python -m pip install --upgrade pip
pip install numpy
pip install scipy
pip install pyx
pip install six
pip install pynomo
```
While the main code works, both for Nomogen and Nomographer, some of my previous nomograms cannot be drawn anymore.

I encounter a NameError when adding **'v_line_color'** for a type 5 nomogram, or modifying text colour and size within **'pyx_extra_defs'**.
The command prompt then returns an error message, respectively : _name 'color' is not defined_ ; _name 'self' is not defined_ ; _name 'type' is not defined_ .
The isopleth personalisation works still.

I do not know python and have not been able to fix this issue.
Any help would be much appreciated.

**Comment by lefakkomies** [comment]
Thanks! Could you send exact versions of python and packages, failing script and error messages?

**Comment by addlamorille** [comment]
Thank you, Sir, for your quick response.
The versions are : 
```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32

Package    Version
---------- -------
numpy      1.21.6
pip        23.2.1
PyNomo     0.3.4
PyX        0.16
scipy      1.7.3
setuptools 39.0.1
six        1.16.0
```
A minimal example of a failing script would be : 
```
from pynomo.nomographer import Nomographer

N_params_1 = {
    'u_min': 0.0,
    'u_max': 10.0,
    'function': lambda u: u,
    'title': r'$u_1$',
    'tick_levels': 2,
    'tick_text_levels': 1,
       'extra_titles':[{'dy':-3,'dx':5,
                      'text':r'text here','width':5,   #this works
                      'pyx_extra_defs':[\
#1                                     color.rgb.white,
#2                                     text.size.LARGE\
                                       ]
                      }],
}

N_params_2 = {
    'u_min': 0.0,
    'u_max': 10.0,
    'function': lambda u: u,
    'title': r'$u_2$',
    'tick_levels': 2,
    'tick_text_levels': 1,
#3  'axis_color':color.rgb.blue,
}

N_params_3 = {
    'u_min': 0.0,
    'u_max': -10.0,
    'function': lambda u: u,
    'title': r'$u_3$',
    'tick_levels': 2,
    'tick_text_levels': 1,
}

block_1_params = {
    'block_type': 'type_1',
    'width': 10.0,
    'height': 10.0,
    'f1_params': N_params_1,
    'f2_params': N_params_2,
    'f3_params': N_params_3,
    'isopleth_values': [[6, 2, 'x']],
}

main_params = {
    'filename': 'ex_type1_nomo_1.pdf',
    'paper_height': 10.0,
    'paper_width': 10.0,
    'block_params': [block_1_params],
    'transformations': [('rotate', 0.01), ('scale paper',)],
    'title_str': r'$u_1+u_2+u_3=0$',
    'debug': False,
    'isopleth_params':[{'color':'green','circle_size':0.0,}],   #this works
       'draw_lines':True,
       'line_params': [{'coords':[[0,4,6,10]],   #this works
                      'line_style':[\
#4                                 color.cmyk.Orange,
#5                                 style.linewidth.thick,
#6                                 style.linestyle.dashed\
                                   ],
                      'circle_size':1.0,'transparency':1.0,   #this works
#7                    'circle_color':color.cmyk.Red,
                      }],
}

Nomographer(main_params)
```
By ignoring the problematic lines of code, it builds up the nomogram, isopleth, extra text and line just fine.
[ex_type1_nomo_1.pdf](https://github.com/lefakkomies/pynomo/files/12642769/ex_type1_nomo_1.pdf)
By removing the 1st hashmark, the error code is : 
```
Traceback (most recent call last):
  File "ex_type1_nomo_1.py", line 13, in <module>
    color.rgb.white,
NameError: name 'color' is not defined
```
There is a similar message for the 3rd, 4th and 7th ones.
For the 2nd hashmark : 
```
Traceback (most recent call last):
  File "ex_type1_nomo_1.py", line 14, in <module>
    text.size.LARGE\
NameError: name 'text' is not defined
```
For the 5th one : 
```
Traceback (most recent call last):
  File "ex_type1_nomo_1.py", line 61, in <module>
    style.linewidth.thick,
NameError: name 'style' is not defined
```
Same error message for the 6th hashmark.

**Comment by addlamorille** [comment]
Thank you for your quick reply, I just found a solution! Simply adding `from pyx import *` in preamble.
Also, `v_line_color` is now `v_axis_color`.
[Fisher_equation.pdf](https://github.com/lefakkomies/pynomo/files/12646548/Fisher_equation.pdf)
Status: open --> closed

**Comment by lefakkomies** [comment]
ok, good to hear. Send private email, if interested to publish your nomograph one day in pynomo-doc.

**Comment by tvrusso** [comment]
Thanks for the tip on what to import to clear this problem.  I had a bit of code rot in some of my old pynomo scripts and in cleaning them up found that I needed to import pyx and math where I didn't have to before.  :clap:
