### ISSUE TITLE
calculation error in ex_second_order_eq.py 

### ISSUE THREAD

**Issue by jonasstein** [lefakkomies/pynomo#5]
ex_second_order_eq.py should solve z^2 + pz + q = 0
returns an isopleth for
```
z=0.3
p=-7
q=2

0.9 +  -2.1 + 2 != 0
```

**Comment by lefakkomies** [comment]
0.3 ** 2 - 7 * 0.3 + 2 = 0.09 - 2.1 + 2 = -0.01 (0.3 is approximation from nomograph).
^^^^^^^^                         ^^^^ 

Is short, no error found.
