### ISSUE TITLE
Can I lie the bar horizontal?

### ISSUE THREAD

**Issue by Williamongh** [lefakkomies/pynomo#8]
Hi, thanks for your work.
I dont like the bar stand straight. Can I lie the bar horizontal? Just like nomogram in R.
Thank you again.

**Comment by lefakkomies** [comment]
I think these R nomograms are not classical nomographs  (see https://stackoverflow.com/questions/38276973/r-how-to-read-nomograms-to-predict-the-desired-variable )

If one wants to rotate nomographs in pynomo, see:
http://lefakkomies.github.io/pynomo-doc/main_params.html?highlight=rotate

Please, only issues here.

**Comment by Williamongh** [comment]
Thanks!
sorry to disturb.
